export enum OrderStatus {
  PLACED = 'PLACED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',

  PICKED_UP = 'PICKED_UP',
  IN_PROGRESS = 'IN_PROGRESS',

  WASHING = 'WASHING',
  IRONING = 'IRONING',
  PACKING = 'PACKING',

  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',

  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}